/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Image from "next/image";

function JobListing() {
  return (
    <div className="items-stretch border bg-white flex flex-col w-full p-6 border-solid border-zinc-200 max-md:mt-8 max-md:px-5">
      <header className="justify-between items-stretch flex gap-5">
        <Image
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/779986c9-5741-4edb-a833-85abe0cea874?apiKey=0ce679486ae447bd8ce08b2cc2263e2e&"
          className="aspect-square object-contain object-center w-12 overflow-hidden shrink-0 max-w-full"
          alt="Company Logo"
        />
        <div className="text-indigo-600 text-center text-base leading-7 justify-center items-stretch border border-[color:var(--brands-primary,#4640DE)] grow px-3 py-1 border-solid self-start">
          Full Time
        </div>
      </header>
      <h2 className="text-slate-800 text-lg font-semibold leading-7 mt-4">
        Brand Designer
      </h2>
      <div className="justify-center items-center flex gap-2">
        <div className="text-slate-600 text-base leading-7 self-stretch">
          Dropbox
        </div>
        <div className="opacity-30 flex w-1 shrink-0 h-1 flex-col my-auto rounded-[50%]" />
        <div className="text-slate-600 text-base leading-7">
          San Fransisco, US
        </div>
      </div>
      <p className="text-slate-500 text-base leading-7 mt-4">
        Dropbox is looking for Brand Designer to help the team t ...
      </p>
      <div className="items-stretch flex justify-between gap-2 mt-4 pr-11 max-md:pr-5">
        <div className="text-emerald-300 text-sm font-semibold leading-6 justify-center items-stretch bg-emerald-300 bg-opacity-10 grow px-4 py-1 rounded-[80px]">
          Design
        </div>
        <div className="text-indigo-600 text-sm font-semibold leading-6 justify-center items-stretch bg-indigo-600 bg-opacity-10 grow px-4 py-1 rounded-[80px]">
          Business
        </div>
      </div>
    </div>
  );
}

export default JobListing;
